github: [devinschumacher]

open_collective: devinschumacher

custom: [
"http://orangepornvideos.net/pornhub-video-downloader",
"https://serpapps.github.io/pornhub-video-downloader/",
"https://serp.co/products/pornhub-video-downloader/reviews/",
]
